import { Inter, Roboto, Montserrat } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["500", "100", "300", "400", "700"],
});
const montserrat = Montserrat({ subsets: ["latin"] });
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"flex flex-row " + montserrat.className}>
        <Navbar />
        {children}
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
