import { Montserrat } from "next/font/google";
const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "../globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  )
}
